### ISSUE TITLE
Docker images 0.3 / 0.3.0 go into restart loop

### ISSUE THREAD

**Issue by mmmmillar** [nhost/hasura-auth#104]
Upgrading from 0.2 (have gone to 0.2.1 for now, works fine)

```
$ node ./dist/start.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/app/dist/start.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.
```

**Comment by plmercereau** [comment]
Hello and many thanks for flagging this.
We just published a [0.3.1 version](https://github.com/nhost/hasura-auth/releases/tag/v0.3.1) that fixes this bug.
[Docker hub link](https://hub.docker.com/layers/nhost/hasura-auth/0.3.1/images/sha256-6e39d5bc720b1042c4d19d53e14ed1d9dce67ace83c1a5c524151bd0a9c4ce80?context=explore)
