### ISSUE TITLE
Hasura auth container fails to start after upgrade from v0.2 to v0.5

### ISSUE THREAD

**Issue by mmmmillar** [nhost/hasura-auth#129]
Migrations are applied correctly on a fresh db, seems to break on existing db

Possibly related to https://github.com/nhost/hasura-auth/commit/445ecb48793009399e5f5d006143c984090de594

```
> hasura-auth@0.5.0 start /app
> node ./dist/start.js

{"level":30,"time":1648739886630,"pid":18,"hostname":"hasura-auth-7fc5bc477c-nh25w","msg":"Hasura is ready"}
(node:18) UnhandledPromiseRejectionWarning: Error: Migration failed. Reason: Hashes don't match for migrations '00002_custom-user-fields.sql'.
This means that the scripts have changed since it was applied.
at /app/node_modules/.pnpm/@djgrant+postgres-migrations@4.1.0-rc.1/node_modules/@djgrant/postgres-migrations/dist/migrate.js:63:27
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async /app/node_modules/.pnpm/@djgrant+postgres-migrations@4.1.0-rc.1/node_modules/@djgrant/postgres-migrations/dist/with-lock.js:24:28
at async applyMigrations (/app/dist/migrations.js:16:9)
at async start (/app/dist/server.js:38:5)
```

**Comment by plmercereau** [comment]
Hello @mmmmillar,
Thanks for this. We'll fix this very soon.

Reproduced with the following steps with the CLI:
1. Create a project with `nhost init`
2. Remove the `.nhost` folder if existing
3. In the `nhost/config.yaml` file, set the Hasura Auth version to `0.2.0`:
```yaml
services:
  auth:
    version: 0.2.0
```
4. Run `nhost -d` and wait until all services has started
5. Stop Nhost
6. Change the Hasura Auth version to `0.5.0` in `nhost/config.yaml`
7. Run `nhost -d`
