### ISSUE TITLE
Passwordless signin should return id of user 

### ISSUE THREAD

**Issue by ArieJones** [nhost/hasura-auth#135]
It would be optimal if the passwordless signup would return the id of the user so that it could be properly used in a scenario such as an Administration flow where you create a user but do not want to create a password 

-- Passwordless response 
https://github.com/nhost/hasura-auth/blob/dc4a4126cd36d73a67d3e0ead07c061cd3a31f9f/src/routes/signin/passwordless/email.ts#L112

-- Signup response 
https://github.com/nhost/hasura-auth/blob/4d452d7d0b374cad7deb3d59422ad973fb4d801e/src/routes/signup/email-password.ts#L123

**Comment by elitan** [comment]
Would it be enough that the user id is only returned if a user is created during the passwordless signing flow?

The problem with always returning the user id is that now anyone can get the user id of any email in your system.
