### ISSUE TITLE
local docker compose setup not working

### ISSUE THREAD

**Issue by ejkkan** [nhost/hasura-auth#139]
Computer: Apple M1 Max 2021

Running example docker compose file from this repo results in an unhealthy container.

Steps:
1: installing steps from: https://docs.nhost.io/reference/hasura-auth/installation
2. run 'docker ps', output  (health: starting)
3. wait for about 1 min
4. run 'docker ps', output  (unhealthy)
5. open localhost:4000/*any path*, this returns:
`{
"status": 404,
"message": "Route not found",
"error": "route-not-found"
}`

The .env setup does not set a AUTH_HOST (which defaults to 0.0.0.0) for this case

Looking at container logs, the hasura-auth container does connect and communicate with the hasura-engine. Setting up tables and such, and requests are forwarded to the engeine. 
Example:
`{"level":30,"time":1649873380080,"pid":18,"hostname":"aaf913af8c03","req":{"id":1,"method":"GET","url":"/","query":{},"params":{},"headers":{"host":"localhost:4000","connection":"keep-alive","cache-control":"max-age=0","sec-ch-ua":"" Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":""macOS"","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","accept-encoding":"gzip, deflate, br","accept-language":"en-US,en;q=0.9,sv;q=0.8,nb;q=0.7"},"remoteAddress":"192.168.16.1","remotePort":59052},"res":{"statusCode":404,"headers":{"x-dns-prefetch-control":"off","x-frame-options":"SAMEORIGIN","strict-transport-security":"max-age=15552000; includeSubDomains","x-download-options":"noopen","x-content-type-options":"nosniff","x-xss-protection":"1; mode=block","access-control-allow-origin":"*","surrogate-control":"no-store","cache-control":"no-store, no-cache, must-revalidate, proxy-revalidate","pragma":"no-cache","expires":"0","content-type":"application/json; charset=utf-8","content-length":"68","etag":"W/"44-D28JDVc1oIeEP0+yZeNCuePzo94""}},"responseTime":15,"msg":"request completed"} 
`

If I update it to AUTH_HOST: localhost. Following happens:
1: installing steps from: https://docs.nhost.io/reference/hasura-auth/installation
2. run 'docker ps', output: (health: starting)
3. wait for about 1 min
4. run 'docker ps', output  (healthy)
5. open localhost:4000/*any path*, the page is not found.

However, when it's in a healthy state, the container can't be reached. I can see that the docker container is running on port 4000, but localhost:4000 is not connected to anything/return nothing.
I can see that the container is never reached in the containers logs.

**Comment by ikapo** [comment]
Same happens to me on Ubuntu Server 20.04

**Comment by plmercereau** [comment]
Hello,
Here's [a pull request that proposes to remove the use of the `AUTH_HOST` environment variable](https://github.com/nhost/hasura-auth/pull/141), as it complexifies things without a clear added value.

In the meantime, could you check if [this docker-compose](https://gist.github.com/plmercereau/7565e6064854847cf220ddc723e30ecf) solves your issue?
It is basically a copy of the original example, with AUTH_HOST set to 0.0.0.0, and the corrected healthcheck

**Comment by ejkkan** [comment]
Unfortunately neither of these makes a difference. I'm kinda feeling that it is not the AUTH_HOST flag that is the problem.

Have tried running the docker compose file with the master branch and the PR. They run hasura on localhost:8080 and hasura auth on localhost:4000
- localhost:4000/healthz gives OK
- localhost:4000/v1/auth/* gives 
`{
"status": 404,
"message": "Route not found",
"error": "route-not-found"
}`
- localhost:8080/v1/auth/* gives:
`{
"path": "$",
"error": "resource does not exist",
"code": "not-found"
}` 

I am running on a Silicon Macbook Pro  
I have tried running with docker compose v1/v2 config.
docker version 20.10.12
docker compose v2.2.3

I have setup a standalone React project to test a [deplyed instance with nhost ](https://tcswntbdgyburorycxbh.nhost.run/), an everything working fine.

This might a bit off-topic for the original issue, but just to show that I've tried all the different solutions that I've stumbled upon.
I have tried to run a project set up with nhost-cli throws:

```
I have installed this and all other depedencies)
⚠ Run `npm init && npm i && npm i express` to use functions

✘ Failed to initialize functions server
✔ See you later, grasshopper!%
```

**Comment by plmercereau** [comment]
Hi Erik,

Nhost cloud runs hasura, hasura-auth, hasura-storage and functions, and exposes them through a reverse proxy:
- `/v1/graphql` -> hasura
- `/v1/auth` -> hasura-auth
- `/v1/storage` -> hasura-storage

The docker-compose you used shows how to run hasura-auth together with hasura, but does not mimick how nhost cloud works.
As a result, instead of using `localhost:4000/v1/auth/*`, you should use `localhost:4000/*`. 

If your primary goal is to use the same nhost cloud endpoints locally, then the Nhost CLI is indeed a good start (about the above cli isssue, I suggest you go have a look at the [Nhost CLI issues](https://github.com/nhost/cli/issues), or reach out with the team on Discord). If you want to use docker-compose to use the exact same Nhost endpoints, please have a look at [the example from our main repository](https://github.com/nhost/nhost/tree/main/examples/docker-compose).

I hope this helped
