### ISSUE TITLE
MFA backup codes

### ISSUE THREAD

**Issue by masterbater** [nhost/hasura-auth#151]
- Session Management (Logout from other sessions or particular session)
- Backup Codes In case MFA is lost or forgotten
- Webauthn Yubikey

**Comment by plmercereau** [comment]
> * Session Management (Logout from other sessions or particular session)
you can sign out to all connected devices in adding `{ "all": true }` to the http post payload on the `/signout` endpoint.
See the [/signout endpoint in the api reference](https://docs.nhost.io/reference/hasura-auth/api-reference)

> * Backup Codes In case MFA is lost or forgotten
> * Webauthn Yubikey
I renamed this issue for MFA backup codes, and created a separate issue for Webauthn Yubikey

**Comment by masterbater** [comment]
> > * Session Management (Logout from other sessions or particular session)
> 
> you can sign out to all connected devices in adding `{ "all": true }` to the http post payload on the `/signout` endpoint. See the [/signout endpoint in the api reference](https://docs.nhost.io/reference/hasura-auth/api-reference)
> 
> > * Backup Codes In case MFA is lost or forgotten
> > * Webauthn Yubikey
> 
> I renamed this issue for MFA backup codes, and created a separate issue for Webauthn Yubikey #153

Thanks for pointing it out about signing out on all of the device. I also figure out how to list and handle by retrieving the refresh_tokens table
