### ISSUE TITLE
do you have any example using Oauth providers?

### ISSUE THREAD

**Issue by cocodrino** [nhost/hasura-auth#152]
Hi, this seems really promising, love the fact about how simple is use it for user/password authentication, but the documentation using oauth providers seems not be enought, do you have some examples or documentations about how use it? thank you!

**Comment by elitan** [comment]
yes, here's some documentation:

https://docs.nhost.io/platform/authentication/sign-in-with-google
https://docs.nhost.io/platform/authentication/sign-in-with-facebook
https://docs.nhost.io/platform/authentication/sign-in-with-github
https://docs.nhost.io/platform/authentication/sign-in-with-linkedin
https://docs.nhost.io/platform/authentication/sign-in-with-spotify

You can check the environment variables for the providers here: https://github.com/nhost/hasura-auth/blob/main/src/config/providers.ts
