### ISSUE TITLE
env var to disable sso signup

### ISSUE THREAD

**Issue by mmmmillar** [nhost/hasura-auth#157]
Hi, would you consider an env-var-enabled enhancement that allows SSO login for existing accounts, but disables SSO signup? Atm if you login with Google and a user does not exist it creates a user and logs them in.

eg AUTH_PROVIDER_SIGNUP_ENABLED (true by default)

**Comment by elitan** [comment]
I think this is a good idea.

In the meantime, you can use the `AUTH_ACCESS_CONTROL_*` env vars to block/allow emails to sign up.
