### ISSUE TITLE
Hasura-auth doesn't check/capture invalid locale when using Oauth

### ISSUE THREAD

**Issue by alveshelio** [nhost/hasura-auth#158]
When logging or signing up with a social network it hangs on the callback.
The request to `https://www.linkedin.com/oauth/v2/authorization-submit?app_id=...` goes through, however, the request to `http://localhost:1337/v1/auth/signin/provider/linkedin/callback?code=...&state=...` hangs.

**Comment by nunopato** [comment]
I am closing this issue in favor of https://github.com/nhost/hasura-auth/issues/44

**Comment by nunopato** [comment]
I am closing this issue in favor of https://github.com/nhost/hasura-auth/issues/44
