### ISSUE TITLE
Can the callbackURL be specified as parameter?

### ISSUE THREAD

**Issue by yannickglt** [nhost/hasura-auth#166]
In our organization, we have only one instance of `hasura-auth` in production but it is pointed by several domains (`auth.foo.io`,  `auth.foo.bar`, etc). 
We would like to be redirected to the original `hasura-auth` URL after login.

Currently, we are always redirected to the [AUTH_SERVER_URL ](https://github.com/nhost/hasura-auth/blob/9c6d0f4ded4fc8fd1b8031926c02796c74a7eada/src/routes/signin/providers/utils.ts#L249). 

It would be nice to allow specifying the full callbackURL as parameter of the login call to override it.

Let me know what do you think about it.

**Comment by plmercereau** [comment]
Hello Yannick,
Please correct me if I misunderstood your suggestion.

Some actions are indeed redirected to `AUTH_SERVERL_URL`, and this cannot be changed as this redirection is required to complete certain tasks, for instance to handle the authentication confirmation from an Oauth provider, to confirm an user verified their email when clicking on a confirmation link etc.

However, once this action is done, Hasura Auth redirects to `AUTH_CLIENT_URL` and adds the refresh token to the query parameter so the frontend can use it to get the access token (jwt).

`AUTH_CLIENT_URL` is required, and you can pass additional urls in the comma-separated `AUTH_ACCESS_CONTROL_ALLOWED_REDIRECT_URLS` environment variable.

That being said, I just suggested [any redirection url would work by default, as long as a valid `redirectTo` url is passed as an option to the request](https://github.com/nhost/hasura-auth/pull/167).

**Comment by yannickglt** [comment]
Hi,

First, thanks for your fast answer.

Then, it's actually related to the AUTH_SERVER_URL variable.

I wondered if, to tackle the confirmation from OAuth providers, this variable could not be sent during the initial provider call as URL parameter. 
For the second example, when clicking on an email to verify the user, I guess the server URL could be passed as URL parameter in the request which triggered the email send.

I understand it looks to be hard to handle. If you have other suggestions to tackle my problem, I'm open to ear them 🙂

Thanks again.

**Comment by elitan** [comment]
I'm not following exactly why you want to change the `AUTH_SERVER_URL`. I guess it's related to what you wrote here:

> In our organization, we have only one instance of hasura-auth in production but it is pointed by several domains (auth.foo.io, auth.foo.bar, etc).

So maybe a better question is, why do you have multiple domains pointing to the same Hasura Auth service? What's the use case?

**Comment by elitan** [comment]
What was the solution? It might be valuable for other developers who are experiencing the same thing?

**Comment by yannickglt** [comment]
We duplicated the instances during the migration thenwe removed the old one after some weeks.
