### ISSUE TITLE
Verify Password Request

### ISSUE THREAD

**Issue by joshmedeski** [nhost/hasura-auth#17]
# User Story
As a user, when I update sensitive information on my account, I want to enter my password again for extra security.

# Description
I'd like to add an endpoint that allows you to send a password and email, or user_id, and return a 200 if that password is correct. This can be used in the front-end for sensitive updates (ex: changing an email, adding a credit card, etc...).

GitHub does this when you make changes to SSH keys as another example.

**Comment by elitan** [comment]
Would it be enough to send a sign-in request (`/signin/email-password`) with email and password and check if it returns `200` back?

**Comment by elitan** [comment]
@joshmedeski Any thoughts on my previous comment? Would that approach be enough for now?

**Comment by joshmedeski** [comment]
@elitan that could work but I'm no longer actively working with hasura-auth.
