### ISSUE TITLE
Session isn't renewing automatically an expires causing problems.

### ISSUE THREAD

**Issue by alveshelio** [nhost/hasura-auth#174]
When a user is logged in and he's inactive for a moment the session expires and causes errors in the console. The session should renew automatically. 

![image](https://user-images.githubusercontent.com/8176422/171019400-596558ee-c3d0-4fe7-aab8-79117029e65a.png)

**Comment by nunopato** [comment]
@alveshelio this has been fixed and will be released soon.

**Comment by elitan** [comment]
Should be fixed by the latest releases of Hasura Auth and `@nhost/nhost-js`.
