### ISSUE TITLE
Make sure correct email variables are available for all email templates.

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-auth#179]
E.g. the variable `email` is missing here:

https://github.com/nhost/hasura-auth/blob/main/src/routes/user/email/change.ts#L74-L80

The variables we say are available: https://docs.nhost.io/platform/authentication/email-templates#variables

- link
- serverUrl
- clientUrl
- redirectTo
- ticket
- displayName
- email
- locale

I also think we could add the following variable to all email templates:

- newEmail

**Comment by dikshatekriwal** [comment]
@plmercereau is this fixed as I'm see seeing ${email} and not the actual value today?
![image](https://user-images.githubusercontent.com/15191000/172856554-7cbeaa18-5df0-4347-b659-e8c323f6e792.png)

**Comment by elitan** [comment]
We'll roll out this to Nhost Cloud in the next few days.
