### ISSUE TITLE
Magic links break when Outlook safe links are enabled

### ISSUE THREAD

**Issue by mmmmillar** [nhost/hasura-auth#189]
Magic links don't work from Outlook when safe links are enabled. 

The logs show that the verifyHandler is called multiple times when the link is clicked (as part of the safety check) - the first time the ticket is removed from the user record and redirect is called correctly, but this is cancelled out by the subsequent calls to verifyHandler where the ticket no longer exists and an error response is sent.

The code where this happens is here:
https://github.com/nhost/hasura-auth/blob/9f5cbbcd14d3ed1ab2c7fb3b19fccaa3379861d6/src/routes/verify/verify.ts#L33-L62

**Comment by elitan** [comment]
I've googled a bit and seems to be a common issue.

- https://github.com/FusionAuth/fusionauth-issues/issues/629#issuecomment-832778247
- https://github.com/authelia/authelia/issues/2994
- https://github.com/nextauthjs/next-auth/issues/1840
- https://github.com/nextauthjs/next-auth/pull/3900/files

In summary, I think there are two solutions:

1. Always return 200 for HEAD `/verify`: `router.head('/verify', (_, res) => res.sendStatus(200));`
2. Don't delete tickets after they've been used, but instead allow the ticket to be reusable until it expires.

**Comment by Haraldson** [comment]
@elitan Did that actually fix the problem? I’m in a similar situation now, and from what I gather reading a lot of issues and tickets all around, it shouldn't have worked?

**Comment by elitan** [comment]
I think it was fixed yes.

Did you experience something else?

**Comment by Haraldson** [comment]
I haven’t really tried it out yet, but I was asking due to comments such as the ones on [this StackOverflow issue](https://stackoverflow.com/a/67189884), where _disabling_ HEAD requests was said to not work. However, returning a smile and a thumbs up like your fix here might work [differently].

**Comment by lordkev** [comment]
Unfortunately, this solution no longer works. In my testing, Outlook makes actual GET requests during its link scanning, not just HEAD requests.

**Comment by kelkes** [comment]
I've got the same problem with magic links. Links are invalid before the user got the chance to click it.

**Comment by dbarrosop** [comment]
We wrote about this issue recently:

https://nhost.io/blog/protect-magic-links-from-email-clients
https://github.com/nhost/nhost/pull/2590

**Comment by psycho-baller** [comment]
I made a video on how you can fix this issue:
https://youtu.be/fkUPlmiNPoc
