### ISSUE TITLE
Implement SMS Templates for Auth

### ISSUE THREAD

**Issue by elleryfamilia** [nhost/hasura-auth#196]
Currently the SMS that goes out says "Your code is 000000"

Ideally we are able to customize a template and insert the code as a variable:

*Nhost - Here is your code: {{verification_code}}. Don't share it with anyone*

To push things even further, you could even make Auth variables available for the templates:

*{{first_name}}, here is your code: {{verification_code}}. Don't share it with anyone*

**Comment by plmercereau** [comment]
A `AUTH_SMS_TEMPLATE` may be the quickest way forward, but we would miss translations. Eventually we will likely need to implement the same system as for email templates

**Comment by L3K0V** [comment]
Can I pick this up next days? I can implement the template approach.

**Comment by plmercereau** [comment]
Yes, definitely!
