### ISSUE TITLE
Magic Link with no user creation

### ISSUE THREAD

**Issue by anelad** [nhost/hasura-auth#201]
I need to disable new user creation during magic link process.
I will create users manually and non-existing users trying to log in via magic link should get user not found error.
Can I achieve this behavior in this version?

**Comment by anelad** [comment]
> > Can I achieve this behavior in this version?
> 
> Not directly, but I think you can add a single random email to "allowed emails" so no one will be able to sign up. Existing users can still sign in.

For those who wants to achieve the same behaviour @elitan's suggestion was working until today. Now, I suggest checking if an user with given email already exists or not by using admin secret header like smth like this:

```typescript

const GET_USER_BY_EMAIL_QUERY = `
  query getUserByEmail($email: citext) {
    users(where: { email: { _eq: $email } }) {
      id
    }
  }
`;
async function checkUserExists(email: string) {
  const { data, error } = await nhost.graphql.request(
    GET_USER_BY_EMAIL_QUERY,
    { email },
    { headers: { "x-hasura-admin-secret": process.env.adminSecret! }}
  );
  return data.users.length ? true : false
}

...
...
...

async function signIn(email) {
  const userExists = await checkUserExists(email)
  if (userExists) {
    // show error
    return
  }

  // do login
}
```

**Comment by kelkes** [comment]
@dbarrosop Is it possible to reopen this? I have the same problem:

I want to allow user sign up but not automatically when they sign in with magic link. It leads to confusion with clients login in with different email addresses then they sign up and seeing an empty app

**Comment by dbarrosop** [comment]
what exactly do you need to do? Asking because what the OP requested is now possible with:

```
[auth.signUp]
enabled = true
```

config above will prevent users from signing up so have to pre-create them manually beforehand (which is what this issue was about originally)

**Comment by kelkes** [comment]
Allow People to sign up via a form using the sign up functions from nhost BUT don't auto sign up people when they use magic link login.

**Comment by dbarrosop** [comment]
ok, makes sense. I'd suggest opening a new issue to avoid confusion as this is a slightly different issue and it is covered already by existing functionality. Thanks!
