### ISSUE TITLE
Magic Link - creation without sending emails

### ISSUE THREAD

**Issue by jogri** [nhost/hasura-auth#202]
I need a way to generate a magic link without it being sent to the specified email address.
Right now I only can think about workarounds by stopping the email from being sent (on the smtp server side) and get the token from the database manually or set up a webhook in hasura.
So basically it would be awesome to have the ability to just generate the magic link token in the database without the whole email workflow.
Another possibility is the suggested webhook system #169 that could trigger nhost functions - but I think I prefer to set these webhooks in hasura.

**Comment by pk992** [comment]
This would be so helpfull for cases where additional logic needs to be run on registration (first login with magic link).

**Comment by wilsonbright** [comment]
Hey team, is this being planned? any update on this?

**Comment by dbarrosop** [comment]
No, this work isn't on our roadmap. However, if someone is willing to contribute it we'd be willing to discuss the use case and potential solutions.
