### ISSUE TITLE
Database migrations deadlock when starting with a fresh DB.

### ISSUE THREAD

**Issue by Tiim** [nhost/hasura-auth#221]
I'm trying to use hasura-auth as a selfhosted service with docker. In development this works really nice. Now I want to deploy my application and I got stuck on the following:

- hasura-auth does not run the migrations because hasura is not started up. (Hasura is not ready. Retry in 5 seconds.)
- hasura tries to apply the migrations before starting up (dockerfile: hasura/graphql-engine:v2.8.4.cli-migrations-v3), but fails because some tables have a foreign key that link to the users table which does not exist yet.

Now both hasura and hasura-auth are in a deadlock where both are waiting for each other to apply the migrations.

It would be nice if hasura-auth could apply the database migrations even if hasura has not started yet.

**Comment by Bernix01** [comment]
This issue is still valida (? closed and marked stale...

**Comment by dbarrosop** [comment]
Following the conversation here: https://github.com/nhost/hasura-auth/pull/389#issuecomment-1773915106
