### ISSUE TITLE
Cannot use custom claim array values

### ISSUE THREAD

**Issue by L3K0V** [nhost/hasura-auth#222]
First I have defined custom claim like this:

```
AUTH_JWT_CUSTOM_CLAIMS: '{"my-property-ids":"properties.id"}'
```

When user have properties, in the token I expect to have array with the IDs of these properties

I update table permissions like following:

![image](https://user-images.githubusercontent.com/2267270/182029252-7bc4c8f9-8c43-4734-80d0-150ff2bc6f8f.png)

### Scenario 1: When there's no matching property IDs

```
{
  "errors": [
    {
      "extensions": {
        "code": "data-exception",
        "path": "$"
      },
      "message": "malformed array literal: \"null\""
    }
  ]
}
```

### Scenario 2:  When there's only one matching property ID

```
{
  "errors": [
    {
      "extensions": {
        "code": "data-exception",
        "path": "$"
      },
      "message": "malformed array literal: \"AuSoCKNydqpMqCGEixTdQ\""
    }
  ]
}
```

### Scenario 3: When there's more then one matching property IDs

Everything looks to be working.

Is there something I'm doing wrong?

**Comment by plmercereau** [comment]
You'd rather try
```sh
AUTH_JWT_CUSTOM_CLAIMS: '{"my-property-ids":"properties[].id"}'
```
See [JSONata's official documentation](https://docs.jsonata.org/predicate#singleton-array-and-value-equivalence)

**Comment by shiftlabs1** [comment]
> JSONata's official documentation

@plmercereau nhost cloud permission variables does not allow the capture of square brackets []. how does one handle this ?

**Comment by plmercereau** [comment]
The Nhost cloud is being updated, it will be available soon.
We also need to upgrade its hasura-auth version to 0.12

Reopening this issue until this is solved in the cloud

**Comment by plmercereau** [comment]
Hasura-auth `0.13.2` is deployed in the cloud. Closing. Thanks for your patience
