### ISSUE TITLE
how to deploy with vercel please help me 🙏

### ISSUE THREAD

**Issue by chanthavong** [nhost/hasura-auth#229]

**Comment by plmercereau** [comment]
Hello @chanthavong,
Hasura auth cannot be deployed in Vercel: it is a backend application, and it doesn't fit in functions.
You can use hasura-auth out of the box on [Nhost](nhost.io) or deploy the [docker image](https://hub.docker.com/r/nhost/hasura-auth) in the infrastructure of your choice.
Good luck!
