### ISSUE TITLE
Storing refresh token & access token in plain text (OAuth providers)

### ISSUE THREAD

**Issue by ilijaNL** [nhost/hasura-auth#230]
Hello, I wonder how refresh tokens and access tokens from auth providers are stored? Quickly expecting the code I assume it is stored as plain text. Especially for the refresh token, it seems like a security risk and is equivalent to storing the password as plain text. Which means that when a data leak occurs, the refresh token can be used by the hacker to authenticate and potentially use the tokens to make request on behave of the user.

Or I am possibly wrong?

**Comment by elitan** [comment]
If you mean tokens to OAuth providers stored in `auth.user_providers`, then yes, they are stored in plain text.

If you mean refresh tokens used to sign in, they are also stored in plain text. These I think we can hash without any problem.

The OAuth tokens are a bit think. Those can not be hashed as they are used to communicate with the OAuth provider, but maybe there is a more secure way of managing tokens from OAuth providers?

**Comment by ilijaNL** [comment]
Personally I see refresh tokens from auth providers same as passwords, thus the should be not be stored as plain text.

I am not sure what the best practises about store oauth2 refresh tokens. The only way of making it more secure is to let the user store it in http only cookie and not in database.

**Comment by MaxSchilling** [comment]
@elitan Any chance the hashing has been implemented already? Pretty sure this would bump up in our pentest as well otherwise :-/

**Comment by elitan** [comment]
> Personally I see refresh tokens from auth providers same as passwords

They are not the same as passwords because you give granular access to the service (e.g. Google). By default, this means you give access to Hasura Auth to **read** the user's name, profile picture, and email.

> Any chance the hashing has been implemented already?

Nothing has been implemented regarding this issue yet.

**Comment by elitan** [comment]
Maybe we should encrypt the tokens to prevent them from being used in case they are leaked/hacked from the database.

The tokens can then be decrypted using a key which we could have a [system environment variable](https://docs.nhost.io/platform/environment-variables#system-environment-variables). This way, a serverless function that wants to use a token to interact with the external service can do so by first decrypting the token using the system environment variable.

What do you think @plmercereau and @nunopato?

**Comment by plmercereau** [comment]
Which token are you talking about? I don't understand why we would want to decrypt refresh tokens in functions. Access tokens can't be sent encrypted to the client as they won't be JWT anymore.

As per the initial suggestion, refresh tokens have a similar level of sensitivity as password as users can authenticate with them. I think the suggestion makes sense.

On an implementation standpoint, it is a bit more complicated. Until now, when a refresh token is received by hasura-auth, we look for it in the database with a `SELECT WHERE`. We don't be able to do it that way when the hash is stored. We would need to expose the user id to the client so it can send both the refresh token and the user id, and so we can find the hash through the user id.

IMO it's worth it

**Comment by ilijaNL** [comment]
Can I ask why the oauths refresh token is stored anyway currently?

**Comment by elitan** [comment]
> Can I ask why the oauth refresh tokens are stored anyway currently?

So your app can act on behalf of the user for that system.

We're defaulting to only email, display name, and profile picture. But if you set custom scopes, you can do much more depending on the scopes and service.

As an example, let's say you're building a music application and you let users sign in with Spotify. You set the scopes so you can read the users' playlists on Spotify. In your app, you want to sync the playlists using a cronjob every hour to your application.

This is possible by having Spotify access/refresh tokens for each user in the database.

**Comment by ilijaNL** [comment]
So if you can set the scopes, like editing my google display name, the refresh token should definitely be carefully and securly stored...

**Comment by elitan** [comment]
Just to be clear: The default scopes with Hasura Auth is **READ ACCESS ONLY**.

I still think we should consider encrypting the tokens for OAuth providers.
