### ISSUE TITLE
Gravatar should not be fetched if blank

### ISSUE THREAD

**Issue by GavanWilhite** [nhost/hasura-auth#236]
Right now it seems like a default blank Gravatar is being fetched if one does not exist for the user. 

I believe this means that it can never be overridden by a user photo derived from social login.

I did a little research and I think that this should do the trick:

When Gravatar images are fetched, append d=404 as a query param, as this will cause Gravatar to return a 404 status rather than a default blank image when fetching it. We then need to handle the 404 and set the profile picture to null.

**Comment by GavanWilhite** [comment]
How can that be done on nhost.io? @plmercereau 

When I go to set an environment variable for it, I get the error:

Warning
The environment variable name cannot start with a value that is reserved for an internal environment variable.

**Comment by plmercereau** [comment]
It is possible to set it in the config section, but there's a bug we are working on:
https://github.com/nhost/nhost/issues/880

**Comment by GavanWilhite** [comment]
How would I set it then? @plmercereau

**Comment by plmercereau** [comment]
To Settings -> Sign-In Methods -> Show Advanced Features

**Comment by GavanWilhite** [comment]
Got it, thx
