### ISSUE TITLE
Azure AD integration

### ISSUE THREAD

**Issue by yannickglt** [nhost/hasura-auth#243]
We use Microsoft Azure AD in our company and I would like to use it for Hasura authentication. 

Would you agree if I create a pull request to support Azure AD login using the https://github.com/AzureAD/microsoft-authentication-library-for-js library? Is there a way to chat together if I need help somewhen?

Thanks

**Comment by elitan** [comment]
Thanks for the initiative.

Yes, we would accept a PR like that.

We're on Discord if you need to chat: https://nhost.io/discord
