### ISSUE TITLE
Track Unsuccessful attempts and Lock User

### ISSUE THREAD

**Issue by im-what-im** [nhost/hasura-auth#250]
New Feature request to track unsuccessful login attempts from a user and lock the user after certain (configurable) number of attempts.

**Comment by pkreipke** [comment]
I second this. Also logging attempts at username guessing/"phishing".

**Comment by im-what-im** [comment]
Yes, when the user attempts to sign in with the inbuilt username/password combination, the user should get locked after certain number of unsuccessful attempts, and should probably get a ticket generated to unlock via email.
