### ISSUE TITLE
AUTH_JWT_CUSTOM_CLAIMS not working

### ISSUE THREAD

**Issue by apperside** [nhost/hasura-auth#252]
Hello,
I am running the docker-compose example and it works fantastically!
However, I am trying to add custom claims to my jwt token by following this guide https://github.com/nhost/hasura-auth/blob/main/docs/recipes/custom-hasura-claims.md.

This is my `docker-compose.yaml` and `.env` file
<img width="779" alt="Screenshot 2022-09-29 at 10 47 10" src="https://user-images.githubusercontent.com/5955338/192985817-0e29a96b-2b11-494e-bfd2-185f04732b60.png">

This is a short terminal session inside the nhost/auth docker container

<img width="673" alt="Screenshot 2022-09-29 at 10 51 22" src="https://user-images.githubusercontent.com/5955338/192986846-3fd854db-7f1c-4703-bf27-dc6b867c4c48.png">

If I set an invalid json, I can see in the logs that it fails to parse it, so nhost is reading it for sure.

I also tried the following
```

AUTH_JWT_CUSTOM_CLAIMS={"Organisation-Id":"user.id"}
AUTH_JWT_CUSTOM_CLAIMS={"X-Hasura-Organisation-Id":"user.id"}
AUTH_JWT_CUSTOM_CLAIMS={"x-hasura-organisation-id":"user.id"}
```

No matter how I set it, my JWT token keeps being something like this:

```json
{
  "https://hasura.io/jwt/claims": {
    "x-hasura-allowed-roles": [
      "me",
      "user"
    ],
    "x-hasura-default-role": "user",
    "x-hasura-user-id": "84427969-c7b0-4660-b6ad-c352d9859618",
    "x-hasura-user-is-anonymous": "false"
  },
  "sub": "84427969-c7b0-4660-b6ad-c352d9859618",
  "iat": 1664439916,
  "exp": 1664440816,
  "iss": "hasura-auth"
}
```

What am I doing wrong?

Thank you

**Comment by plmercereau** [comment]
Hello @apperside,
thanks for your kind feedback.
The root of the custom claim value is the current user. As a result, if you want to access the user id, you should use `id` instead of `user.id`:
```
AUTH_JWT_CUSTOM_CLAIMS={"my-claim":"id"}
```
It will generate a `x-hasura-my-claim` value with the id of the user.
You can have a look at [this small guide](https://github.com/nhost/hasura-auth/blob/main/docs/recipes/custom-hasura-claims.md).

I hope this helps

**Comment by apperside** [comment]
Hello @plmercereau ,
thanks a lot for your response!
The guide you linked is the one I had alread read, but I didn't realized that the root was the user object, my bad! 
Thanks a lot for you response

**Comment by plmercereau** [comment]
You're very welcome! Don't hesitate to update the guide to make it a bit clearer for other users that would bump into the same issue :)
