### ISSUE TITLE
E-mail subject template containing special chars brakes the system

### ISSUE THREAD

**Issue by anelad** [nhost/hasura-auth#255]
I was creating Turkish e-mail templates and saw that `subject.txt` containing special chars like `Ü,Ö,Ş,Ç etc` brakes the e-mail send process. 500 error is thrown.

I've tested `body.html` if the problem exists there too, but nope, all good.

Also, the problem might be platform specific. On my local platform (macOS 16) I don't came into that problem.

**Comment by elitan** [comment]
Hi @anelad 

I just tried and I wasn't able to reproduce this:

<img width="939" alt="CleanShot 2022-11-23 at 13 00 13@2x" src="https://user-images.githubusercontent.com/331818/203541719-787e3bf5-f885-4196-a3b2-5869d28ccbd3.png">

Do you think this has been fixed or what steps should I do to reproduce this issue?
