### ISSUE TITLE
Disable sign up and only allow admin users to create new accounts

### ISSUE THREAD

**Issue by Anan7Codes** [nhost/hasura-auth#267]
Hey, would be great if we can disable sign-up and have an admin account only through which we can create new accounts. 

This is kinda for my use case where I'm building a portal and I don't want to let the public sign-up instead, once all the documents are ready and verified, and only then do I create an account for my merchant to use my platform.

**Comment by davidpanic** [comment]
This is very much needed for our use case as well, because in our use case a user that is registered and not assigned any tenants doesn't have access to anything. Currently my workaround is to just deny access to the signup endpoint at our ingress reverse proxy.
