### ISSUE TITLE
Hasura Allow List -  Nhost queries are missing

### ISSUE THREAD

**Issue by AlexMichels** [nhost/hasura-auth#268]
I ran into an issue trying to activate Hasura allow list.
I cannot use signup or other auth queries after activating allow-list, because the nhost Hasura-auth 
queries are missing in the allow list. 
I can only find Rest e.g. POST /signup/email-password.
How to find the correct GraphQL queries which nhost uses for Hasura-auth ?

Would be great if I could activate the allow-list to improve security.

**Comment by elitan** [comment]
I think they are all listed here: https://github.com/nhost/hasura-auth/tree/main/src/gql

Is that enough? Or any way we can make them more available?

**Comment by MaxSchilling** [comment]
For anyone struggling with this, the biggest issue was getting the storage queries, as they are not directly stated in the hasura_storage repository. We tracked them via the hasura logs while testing on localhost via Docker.

Adding these two additional queries will suffice for reading and adding files (please note, no deletion mutation tested yet).

`query ($id: uuid!) {
  file(id: $id) {
    id
    name
    size
    bucketId
    etag
    createdAt
    updatedAt
    isUploaded
    mimeType
    uploadedByUserId
  }
}
`

and 

`
mutation InitializeFile ($id: uuid!, $name: String!, $bucketId: String!, $mimeType: String!, $size: Int!) {
  insertFiles(objects: {id:$id,bucketId:$bucketId,mimeType:$mimeType,name:$name,size:$size}) {
    affected_rows
  }
}
`

**Comment by fmanzali** [comment]
In case somebody else needs this too, I gathered the update/delete GraphQL operations by using `tcpdump` on the storage container. 

These are all the operations I whitelisted:

```js
export const INSERT_FILE = gql(/* GraphQL */ `
  mutation InsertFile($object: files_insert_input!) {
    insertFile(object: $object) {
      id
    }
  }
`);

export const GET_FILE = gql(/* GraphQL */ `
  query GetFile($id: uuid!) {
    file(id: $id) {
      ...FileMetadataFragment
    }
  }
  fragment FileMetadataFragment on files {
    id
    name
    size
    bucketId
    etag
    createdAt
    updatedAt
    isUploaded
    mimeType
    uploadedByUserId
    metadata
  }
`);

export const UPDATE_FILE = gql(/* GraphQL */ `
  mutation UpdateFile($id: uuid!, $_set: files_set_input!) {
    updateFile(pk_columns: { id: $id }, _set: $_set) {
      ...FileMetadataFragment
    }
  }
  fragment FileMetadataFragment on files {
    id
    name
    size
    bucketId
    etag
    createdAt
    updatedAt
    isUploaded
    mimeType
    uploadedByUserId
    metadata
  }
`);

export const DELETE_FILE = gql(/* GraphQL */ `
  mutation DeleteFile($id: uuid!) {
    deleteFile(id: $id) {
      id
    }
  }
`);
```
