### ISSUE TITLE
Query Parameters Being Converted to Lowercase

### ISSUE THREAD

**Issue by linden** [nhost/hasura-auth#273]
we rely on query parameters to determine the source of an function call (i.e. `/api/example?source=Nike`) but somewhere along the line `Nike` gets converted to `nike`, this seems to be a recent change that we first noticed about a week ago.

**Comment by elitan** [comment]
From our Discord discussion, it seems like this issue is happening in production only (not locally), right @linden?

If so, this issue might be some Nhost production gateway issue.

**Comment by linden** [comment]
Hi @elitan, yes this is only happening in production (even with the latest version of the nhost CLI), what can we do to address this if it's a production gateway issue?
