### ISSUE TITLE
"Allowed Emails and Domains" and "Disable New Users" not working with Magic Link

### ISSUE THREAD

**Issue by anelad** [nhost/hasura-auth#293]
When I set an allowed domain in Nhost, signInEmailPasswordless still creates a new account for an email that is not allowed.

Same thing for "Disable New Users" option while it's enabled; when I click on the link in the email, user signs in successfully.

**Comment by plmercereau** [comment]
Hello @anelad, 
This should not be possible, here's a link to the tests:
- [should not be possible to sign it when new users are disabled](https://github.com/nhost/hasura-auth/blob/main/test/routes/signin/passwordless/email.test.ts#L87-L97)
- [should fail to sign if email is not valid](https://github.com/nhost/hasura-auth/blob/main/test/routes/signin/passwordless/email.test.ts#L151-L162)

Hence a few questions:
- Are you using the latest version of hasura-auth?
- Are you sure the environment variables are correctly set?
- If yes to both questions, could you describe a bit further into details so we can reproduce?

Thanks

**Comment by anelad** [comment]
@nunopato found the issue few mins ago
