### ISSUE TITLE
Provide way of changing mobile number when using Passwordless SMS Auth

### ISSUE THREAD

**Issue by elleryfamilia** [nhost/hasura-auth#303]
Currently the API does not provide a way to change a user's mobile number  when using SMS auth, unlike the available changeEmail() method available when using Passwordless Email.

**Comment by elleryfamilia** [comment]
@nunopato Any guidance on how to do this at all? Am I good to just update the mobile number on the auth database?

**Comment by guicurcio** [comment]
> @nunopato Any guidance on how to do this at all? Am I good to just update the mobile number on the auth database?

You shouldn't have any issues by changing the user's phone in either the auth tab, database viewer, or hasura console.

*   https://app.nhost.io/\<your-workspace>/\<your-app>/users

![](https://user-images.githubusercontent.com/20285232/211165065-61617592-55dc-4908-8a71-99a1864273c3.png)

I agree on adding a hook, or a prop in our SDK to make this easier.
