### ISSUE TITLE
DB migrations not applied during upgrade from v0.10.0 to v0.17.0

### ISSUE THREAD

**Issue by mmmmillar** [nhost/hasura-auth#308]
Upgrading from v0.10.0 to v0.17.0

Got this when applying Hasura metadata:
![image](https://user-images.githubusercontent.com/52740958/206606790-d3833277-296c-4dcc-8e2f-2e9526de44b9.png)

Checked the db and auth.user_authenticators does not exist

```
docker logs -f 83e89cade061

> hasura-auth@0.17.0 start /app
> node ./dist/start.js

{"level":"info","message":"Log level: info"}
{"level":"info","message":"Waiting for Hasura to be ready..."}
{"level":"info","message":"Hasura is ready"}
{"level":"info","message":"Applying SQL migrations..."}
{"level":"info","message":"SQL migrations applied"}
{"level":"info","message":"Applying metadata..."}
{"level":"info","message":"Metadata applied"}
{"level":"info","message":"Running on port 4000"}
```

**Comment by elitan** [comment]
That's strange.

Can you try this command? What's the output you see?

```SQL
SELECT * FROM auth.migrations;
```

**Comment by mmmmillar** [comment]
I've tried this multiple times by going back to the prev version and clearing the db and then upgrading, get the same result
