### ISSUE TITLE
Docs/Code discrepancy regarding custom oauth scopes

### ISSUE THREAD

**Issue by shivekkhurana** [nhost/hasura-auth#327]
While reading the documentation regarding [auth provider configuration](https://docs.nhost.io/authentication/social-providers-configuration#provider-oauth-scopes), I discovered that:

> Editing scope is not currently supported.

But in the relevant [code](https://github.com/nhost/hasura-auth/blob/8b7a4b158d1145a4c85466916c86a809ae05808d/src/routes/oauth/utils.ts#L106), there is an option to change provider scopes by passing an env variable like:

```
APP_PROVIDER_DISCORD_SCOPE=email,guilds,identity
```

1. Is it safe to use this env variable ?
2. If 1 is `true`, then is the documentation outdated ? 
3. If  2 is `true` then do you accept PRs on the documentation ?

**Comment by plmercereau** [comment]
The feature is supported in hasura-auth, but not available in the Nhost cloud

**Comment by shivekkhurana** [comment]
Okay, then I guess there is no docs to update regarding this.

Closing this issue. Thanks for the quick response ❤️🙏
