### ISSUE TITLE
No Oauth provider 

### ISSUE THREAD

**Issue by victormanuelfrancodev** [nhost/hasura-auth#332]
I'm get this message when I try do a signup ,How can I set this up, I am not able to understand it

``` 
hasura-auth-hasura-auth-1     | {"level":"warn","message":"No Oauth provider"}
hasura-auth-hasura-auth-1     | {"latencyInNs":257000000,"level":"info","message":"POST /v1/auth/signup/email-password 302 257ms","method":"POST","statusCode":302,"url":"/v1/auth/signup/email-password
```

**Comment by plmercereau** [comment]
Hello,
What do you send to the server? What kind of signup do you use? sign up with email+password?
Which version of hasura-auth are you using? (route to get the version: `/v1/auth/version`

**Comment by victormanuelfrancodev** [comment]
Thank you for your answer, I'm using email password, but I don't have idea What am I forgetting to configure?, 
Actually I have my all my tables and schema created by docker compose 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/27299953/212905765-ec2a3f18-27a0-45e5-aa78-70c3dde77878.png">
also My container is running 
![image](https://user-images.githubusercontent.com/27299953/212906056-9cf3fd1f-289b-4b19-955d-5de485d2a9f1.png)
but when I try to do some request  (ok , 3000 port not is up, but why? )
![image](https://user-images.githubusercontent.com/27299953/212906161-1057e56a-0c10-4dc5-b7ed-40da0ed09b88.png)
if I try with port 4000 I got this error 
![image](https://user-images.githubusercontent.com/27299953/212906446-b9f8b054-96fa-47ee-bddf-d61134e88767.png)

Im loosing sorry 😞 
![image](https://user-images.githubusercontent.com/27299953/212906510-dd58e4f0-83e2-4db3-9500-48392c338946.png)

**Comment by victormanuelfrancodev** [comment]
I forgot to say,also mailhog run well 
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/27299953/212907083-7b000646-07f7-43d1-b6e8-7b3d267b1b69.png">

**Comment by victormanuelfrancodev** [comment]
I resolved with : Can you try: http://[myip]:4000/signup/email-password 
My user did create, the email was sent but
Why I got this answer in my request:  
{"session":null,"mfa":null} 
Thank you for your help
