### ISSUE TITLE
Sign in with Apple and Google One Tap

### ISSUE THREAD

**Issue by getlocaladmin** [nhost/hasura-auth#340]
I am looking to implement Sing in with Apple and Google one Tap in react native - native implementation, not web based implementation. I am wondering if Hasura auth would work with that.

Here are the docs:
Apple: https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api
Google:  https://developers.google.com/identity/one-tap/android/idtoken-auth

We plan on using React Native libraries which implements client-side portion in our app.

**Comment by kaashyapan** [comment]
We need this... https://firebase.google.com/docs/auth/flutter/custom-auth
The ability to use 3rd party authentication and generate an Nhost token using Admin SDK.
