### ISSUE TITLE
Allow configuration of returned data on signin

### ISSUE THREAD

**Issue by davidpanic** [nhost/hasura-auth#342]
It would be good to allow configuration of what data is sent back when a user signs in. Currently the entire user object is sent along with the access and refresh token, including the password hash and TOTP secret.

In my opinion there is no need to send all of that, in most projects so far that I've done the most I've needed client-side is the user ID, a display name, an email and maybe the avatar URL if there's a place for it. 

I think it actually might be dangerous to send the TOTP secret as it's supposed to be an out of band authentication factor and the application shouldn't know or care about it at all.

**Comment by davidpanic** [comment]
Still want this.

**Comment by dbarrosop** [comment]
We don't have plans to make the returned object configurable, however, if there is sensitive information we can look into taking it out from the response.

> Currently the entire user object is sent along with the access and refresh token, including the password hash and TOTP secret.

You need the access and refresh tokens, otherwise, why are you signing in?

> including the password hash and TOTP secret.

I don't see those, at least not on the latest hasura-auth.
