### ISSUE TITLE
Oauth Provider SignIn Metadata not parsed as JSON

### ISSUE THREAD

**Issue by im-what-im** [nhost/hasura-auth#357]
While passing the metadata attribute in the query param for the Provider SignIn usecase, the metadata is stored as it is in the metadata column.
No documentation is available for the structure in which metadata is to be passed.
Tried with:
     /provider/{type}?metadata={"key": "value"} 
this got saved in the DB as "{\"key\":\"value\"}"

**Comment by dbarrosop** [comment]
> I think the issue is caused by metadata being sent as a query parameter instead of a json request body

Yes, looking at the original issue it looks like I misunderstood it. We should deserialize the query arg as a json object as they will also be interpreted as a string. The main issue is that if a user wants a literal string they should urlencdode it, for instance `metadata=%22this%20is%20s%20a%20literal%20string%22` for `"this is a literal string"`.

**Comment by dbarrosop** [comment]
#458 should fix this issue
