### ISSUE TITLE
Implicit or PKCE ?

### ISSUE THREAD

**Issue by kaashyapan** [nhost/hasura-auth#390]
Does this library follow the implicit grant auth flow or the Authorisation code with PKCE flow ?
https://developer.okta.com/blog/2018/12/13/oauth-2-for-native-and-mobile-apps

Can someone confirm ?

**Comment by dbarrosop** [comment]
Apologies, we missed this issue. It depends on the provider. If available on the provider side, it relies on the code authorization flow.
