### ISSUE TITLE
Helium for Hasura Starter Kit

### ISSUE THREAD

**Issue by nullxone** [nhost/hasura-auth#393]
Hi! I am using [a modified version](https://github.com/nhost/hasura-auth/pull/385) of this package in the [Helium for Hasura DSL Kit](http://heliumforhasura.com) that I am developing.

Just wanted to share somewhere that your project is being used.

Thanks and regards.

**Comment by dbarrosop** [comment]
Thanks for letting us know. Closing as there doesn't seem anything to do here.
