### ISSUE TITLE
upgrade Nhost .19.3 => .20.1 results in inconsistent metadata

### ISSUE THREAD

**Issue by dohomi** [nhost/hasura-auth#394]
After upgrade .20.1 the Nhost Hasura results in inconsisten metadata. Should `nhost up` not handle the migration automatically?

What are the user steps to fix the inconsistency? basically the whole table of `refresh-tokens` does not load any longer
<img width="1342" alt="Screenshot 2023-05-31 at 15 02 50" src="https://github.com/nhost/hasura-auth/assets/489221/bece4b0d-899f-4043-8758-adcd7e395f7f">

<img width="545" alt="Screenshot 2023-05-31 at 15 04 00" src="https://github.com/nhost/hasura-auth/assets/489221/bbf9afc1-a581-45ed-a5c9-1133543f98ce">

**Comment by dohomi** [comment]
Its actually way worse. The entire refresh_tokens table disappears in the result of trying to solve the migration - afterwards the whole auth package is not usable any longer.

**Comment by nunopato** [comment]
@dohomi what version of the CLI are you using? `v1.0.2` should fix this issue. Please update with `nhost sw upgrade` and let us know if that solves it.

**Comment by dohomi** [comment]
yes the latest version solved it.

**Comment by Kalcode** [comment]
I am not using the nhost, I am using the auth repo for my own self-hosted hasura. I getting the same issue upgrading the repo. What is the CLI doing to fix this that I can do on my side? @nunopato , thanks!

**Comment by dbarrosop** [comment]
hasura-auth updates the metadata itself, the CLI simply downloads it and places it in the right place so it is included in the next deployment (which is specific to Nhost cloud so not relevant if you aren't using it)
