### ISSUE TITLE
nhost  useChangeEmail hook error

### ISSUE THREAD

**Issue by yadudev** [nhost/hasura-auth#422]
i use react nhost hook function useChangeEmail. in some cases it returns an error THE REQUEST PAYLOAD IS INCORRECT.
in which case it occurs ?
i used the code described below
const { changeEmail } = useChangeEmail();

const handleChangeEmail = async () => {
await changeEmail('[yadu.mgu@gmail.com](mailto:yadu.mgu@gmail.com)');
};

**Comment by dbarrosop** [comment]
Please, don't open duplicate issues. This is the third issue you open about this, keep the conversation on the first one:

Closing as duplicate of https://github.com/nhost/nhost/issues/2300
