### ISSUE TITLE
signUp should return userId, email, etc. when registering user with email verification enabled

### ISSUE THREAD

**Issue by beepsoft** [nhost/hasura-auth#43]
Now, when hasura-auth is started from nhost cli with the following config

```yaml
auth:
  email:
    signin_email_verified_required: true
```

and trying to register a user using the JS client's `signUp()` function  it returns

```js
{"session": null, "error": null}
```

It would be good to receive some descriptive data of the newly registered user, at least its `userId` and `email`, so that we could make some operations on the new user even if their email address is not yet validated. 

For example, I would like to assign some new roles to the new user, which I cannot do at `signUp()` time  (ie. I don't want users to be able to register themselves as "editor" but I would have an "admin" user who can assign an "editor" role to selected newly registered users - I do this on the server side)

**Comment by plmercereau** [comment]
related: https://github.com/nhost/nhost/issues/870

**Comment by beepsoft** [comment]
I'm still struggling with this, would be great to receive at least `userId` and `email` even if the email is not yet validated.

**Comment by beepsoft** [comment]
Has this maybe solved? Or is there any problem adding it?
