### ISSUE TITLE
implement AUTH_DISABLE_SIGNUP

### ISSUE THREAD

**Issue by dbarrosop** [nhost/hasura-auth#437]
This feature should basically return an unauthorized error if set to true and a user attempts to signup. This would mean users should be precreated by an admin before they can attempt to sign in (by creating a row into the `users` table containing email/name and locale at least).

**Comment by Matheus-Moreira0** [comment]
Much needed feature!

**Comment by onehassan** [comment]
resolved in https://github.com/nhost/hasura-auth/pull/444

**Comment by dbarrosop** [comment]
0.23.0 introduces:

```
[auth.signUp]
enabled = false
```

(needs latest CLI)
