### ISSUE TITLE
Custom schemes are not allowed to be used as redirectTo values 

### ISSUE THREAD

**Issue by spakanati** [nhost/hasura-auth#439]
It is possible to add "myapp://host" to allowed URLs but then when trying to use the custom scheme as a redirectTo, you get `The+value+of+%22redirectTo%22+is+not+allowed`.

I assume this is not expected behavior, since using custom schemes is the recommended way in the nhost-dart example to [complete sign in with oauth providers](https://github.com/nhost/nhost-dart/blob/main/packages/nhost_flutter_auth/example/lib/oauth_providers_example.dart#L10).

I added an example failing test [here](https://github.com/nhost/hasura-auth/compare/main...spakanati:hasura-auth:custom-schemes).

I did a bit of digging and I think the failure happens [here](https://github.com/nhost/hasura-auth/blob/main/src/validation/fields.ts#L133) because `valueUrl.origin` is null for custom schemes.

**Comment by dbarrosop** [comment]
This should be supported now on 0.30.0.
