### ISSUE TITLE
Allow locale with country in locale in users table

### ISSUE THREAD

**Issue by alveshelio** [nhost/hasura-auth#44]
Right now, the `users` table has a column `locale` which unfortunately only accepts the locale and not the locale plus country. Working with internationalization means that we need to take into account not only the locale but also the country since there's a lot of information that depends on the country.

We should be able to enter `en-ca`, `fr-ca`, `pt-pt`, `pt-br`, etc

**Comment by elitan** [comment]
@alveshelio What is the use case for you? My initial thinking with `locale` was for languages only using [ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) but do you plan to also use it for location/region too?

Would you have different email templates for `pt-pt` and `pt-br`?
