### ISSUE TITLE
ever growing provider_requests table in auth schema

### ISSUE THREAD

**Issue by saibs** [nhost/hasura-auth#455]
We are self hosting hasura auth, we noticed recently that lots of entries are created in provider_requests table in auth schema and keeps on growing because of this [request](https://github.com/nhost/hasura-auth/blob/6c86c490f864f6e84d300cd805df5207b83fc575/src/gql/provider-requests.graphql#L1-L14) triggered in the oauth middleware responsible in creating the session.
Note: we are not using any oauth provider as a signin method.

I think this is happening since this [commit](https://github.com/nhost/hasura-auth/commit/044ed00fcfc101e6c03c02690f86124238156ed2) 
the healthz endpoint moved to app level and every call to healthz endpoint creates an entry in provider_requests table because of the above express middleware.

### Steps to reproduce
- Make sure you are running the auth service without any AUTH_API_PREFIX
- Make a call to /healthz endpoint, which triggers oauth middleware and [creating an entry](https://github.com/nhost/hasura-auth/blob/main/src/routes/oauth/session-store.ts#L26) in provider_requests table

tested on version: 0.24.0
related [discord discussion](https://discord.com/channels/552499021260914688/1186622911981817917/1186622911981817917)

**Comment by dbarrosop** [comment]
Ok, I could reproduce with an empty `AUTH_API_PREFIX`. If you have a solution that doesn't involve changing current behavior a PR is more than welcomed. Otherwise we will try to take a look when we have the time.

**Comment by saibs** [comment]
one easy solution by not affecting current behavior would be to hoist the ```/healthz``` [endpoint](https://github.com/nhost/hasura-auth/blob/00b3994ae1f5f9ee6dab255a1d5343ffbe79906e/src/app.ts#L56) check above the app usage of [router](https://github.com/nhost/hasura-auth/blob/00b3994ae1f5f9ee6dab255a1d5343ffbe79906e/src/app.ts#L25)

but this would still be a vulnerability as one can create lots of entries in the database by just calling random routes which are 404, because of [this](https://github.com/nhost/hasura-auth/blob/00b3994ae1f5f9ee6dab255a1d5343ffbe79906e/src/app.ts#L59) catch all route and would create sessions with null values in provider_requests table
