### ISSUE TITLE
auth.resetPassword throws error when providing options

### ISSUE THREAD

**Issue by alveshelio** [nhost/hasura-auth#50]
When trying to provide an `options` object to `auth.resetPassword` like so:
```ts
auth.resetPassword({ 
  email: 'myemail@email.com', 
  option: { redirectTo: 'http://localhost:3000/en-ca/change-password' }
 })
```
I get a 400 error: Error validating request body. "options" is not allowed. 

`changePassword` accepts `params` of type `ResetPasswordParams`
```ts
export declare type ResetPasswordParams = {
    email: string;
    options?: {
        redirectTo?: string;
    };
};
```

Looking at endpoint `user/password/reset`
```ts
router.post(
  '/user/password/reset',
  createValidator().body(userPasswordResetSchema),
  aw(userPasswordResetHandler)
);
```
`userPasswordResetHandler` accepts following body
```ts
type BodyType = {
  email: string;
  options?: {
    redirectTo?: string;
  };
};
```
And we can see in the code this: `const { email, options } = req.body;`

However, it seems that `userPasswordResetSchema` only accepts the email 
```ts
export const userPasswordResetSchema = Joi.object({
  email: emailRule.required(),
});
```
I've created this PR to fix the issue: https://github.com/nhost/hasura-auth/pull/51

**Comment by nunopato** [comment]
@alveshelio thank you! We will review the PR.

**Comment by TaylorFacen** [comment]
Thanks for posting because I just ran into this as well.

**Comment by plmercereau** [comment]
Thanks for your contribution, the PR has been merged
