### ISSUE TITLE
sign in Refresh token after redirect not match in table refresh_tokens

### ISSUE THREAD

**Issue by chanthavong** [nhost/hasura-auth#520]

**Comment by dbarrosop** [comment]
Please, would you mind elaborating a bit? Thanks!

**Comment by chanthavong** [comment]
example 

1.  https://auth.xxx.com/signin/provider/google/callback
2. https://front.xxx.com?refreshToken=1xxxx-xxxxxx-xxxxxx-xxxxx

but go to  find  1xxxx-xxxxxx-xxxxxx-xxxxx  in table refresh_token  not have data

 Result Error 401

(i use nhost sdk) : NhostClient

help me please  🙏. @dbarrosop

**Comment by dbarrosop** [comment]
Are you self-hosting? In the case read, make sure you understand this document:

https://github.com/nhost/hasura-auth/blob/main/docs/workflows/oauth-providers.md

I suspect your callback configuration is wrong on google's side, it should point to the Auth service, not the application. 

If you are using our cloud refer to our docs: https://docs.nhost.io/guides/auth/social/sign-in-google.
