### ISSUE TITLE
Why remove origin: ENV.AUTH_SERVER_URL  from utils.ts??? Oauth can't work

### ISSUE THREAD

**Issue by bigzhu** [nhost/hasura-auth#522]
Same as
* #452 

I still don't know how to solve this problem.

024258c do some wrong thing, it remove ENV.AUTH_SERVER_URL

If I set AUTH_API_PREFIX="/v1/auth",  oauth set redirect_uri is right, but the other auth url changed from example `https://api.entube.app/v1/auth/v1/auth/signin/provider/github/`, it need two '/v1/auth' to access.

If not set, oauth redirect_uri miss `/v1/auth`, code can't pass

**Comment by dbarrosop** [comment]
Could you provide steps to reproduce so we can help? I.e. a sample docker compose file triggering the issue you are reporting. Thanks!

**Comment by bigzhu** [comment]
I forked the source and made modifications to the commit https://github.com/bigzhu/hasura-auth/commit/2b0bd0795ac8b781929d239d6ec340522fbf8c96. Now, using my self-built image, everything works fine.

The Docker Compose file does not have any special specific configurations.

Use Cloudflare to provide HTTPS.
Use Nginx to proxy  pass.
