### ISSUE TITLE
Accept `pathNames` as valid redirectTo in addition to full URLs

### ISSUE THREAD

**Issue by alveshelio** [nhost/hasura-auth#53]
Looking at `isValidRedirectTo` it only returns `true` if `redirectTo` starts with `ENV.AUTH_CLIENT_URL` (http://localhost:3000)
I'm wondering if we couldn't have a helper to create the `redirectTo`

Right now if we want to send a redirect URL, we need to provide a full URL (http://localhost:300/my-custom-url). However I'm wondering if we couldn't simplify things a bit for the user. 

In my case I'd like to redirect the user to translated URL, so if I'm in `fr-ca` I'd send the user to `http://localhost:300/fr-ca/mon-url-personalise`, otherwise I'd send the user to `http://localhost:300/en-ca/my-custom-url`. However, in order for this to work in dev or prod I'd probably have an environment variable that I'd have to set both in local and in prod, something like `WEBSITE_URL=http://localhost:3000` and then build the url as follow `${process.env.WEBSITE_URL}/en-ca/my-custom-url`.

So what we could allow the user to do is either send a full url or only a portion of the url and we could have a helper function `sanitizeRedirectTo` (I'm sure there's a better name for it) where it would take `redirectTo` and would check if it  would NOT start with either `http` or `https` and would start with `/`, then we would go ahead and build the url for the user like so `${ENV.AUTH_CLIENT_URL}${ENV.AUTH_CLIENT_URL}` then we would check if starts with `ENV.AUTH_CLIENT_URL`.

What do you guys thing about this?

I would gladly create a PR for this :)

**Comment by elitan** [comment]
I'm not sure I understand how this would help.

What are some values of `redirectTo` that you plan to use? Maybe we can start there and see where the current implementation of `isValidRedirectTo` is inadequate.

**Comment by alveshelio** [comment]
What I'd like to use in `redirectTo` would be `/my-custom-redirect` instead of `https://my-site.com/my-custom-redirect`. I don't want to have a environment variable `WEBSITE_URL=localhost:3000` and have to create the same thing in Vercel and then do `${process.env.WEBSITE_URL}/my-custom-redirect` If I want to test this in different environments, how would you go about it?

**Comment by plmercereau** [comment]
Closing because: 
- hasura-auth now accepts any redirect website when no client url is then. It would then become impossible for hasura-auth to construct the full path without knowing the requested base url
- the sdk accepts relative paths and transforms them into absolute paths
