### ISSUE TITLE
Is there a documentation ?

### ISSUE THREAD

**Issue by Mohamed-Kaizen** [nhost/hasura-auth#55]
i was trying to run the [docker-compose.yaml](https://github.com/nhost/hasura-auth/blob/main/docker/dev/docker-compose.yaml), but there is some unknown env variables that i couldn't found even inside the [hasura-backend-plus environment-variables docs](https://nhost.github.io/hasura-backend-plus/docs/environment-variables).

Examples of the env:

* **AUTH_SMS_PROVIDER**: how many provider is there ?, can we add one of local sms providers?
* **AUTH_PASSWORDLESS_SMS_TEMPLATE**: when it's say templates...does it mean path to template or ....

**Comment by elitan** [comment]
Yea sorry we don't have this library particularly well documented. 

To answer your questions:

- The only SMS provider that we support is Twillio
- `AUTH_PASSWORDLESS_SMS_TEMPLATE ` is a string but this env var is currently not used. Instead the SMS message is hard coded ([link](https://github.com/nhost/hasura-auth/blob/main/src/routes/signin/passwordless/sms/sms.ts#L99))

**Comment by elitan** [comment]
You can see the env vars required for SMS auth to work here:

https://github.com/nhost/hasura-auth/blob/main/src/routes/signin/passwordless/sms/sms.ts#L91-L113

I'll close this issue for now but am happy to re-open if necessary.

**Comment by makstr** [comment]
HI @elitan, my understanding is that hasura-auth replaces hasura-backend-plus. Can we safely assume this software will remain open source and will be possible to run independently of the Nhost offering? Just 2 days ago there was a docker/dev directory with example docker-compose.yaml and an .env file. It's gone now. Is there any plan on documenting the env variables and the deployment in the future?

**Comment by elitan** [comment]
Yes Hasura Auth will always remain open source. You can still access the docker-compose.yaml file here: https://github.com/nhost/hasura-auth/blob/main/docker-compose.yaml with the .env.example file here: https://github.com/nhost/hasura-auth/blob/main/.env.example

Hopefully, we'll get better at internal documentation in the future.

**Comment by makstr** [comment]
Cheers, thanks for clarifying and for keeping hasura-auth open source  👍
