### ISSUE TITLE
Development documentation

### ISSUE THREAD

**Issue by beepsoft** [nhost/hasura-auth#56]
It would be great to have some a documentation about how to do development on `nhost-auth` so that we could submit PR-s. I just tried 

`yarn dev`

but it failed with

```
[0] Service 'hasura-auth' failed to build : COPY failed: Forbidden path outside the build context: ../../ ()
error Command failed with exit code 1.
```

because of this line in `docker/dev/Dockerfile`

https://github.com/nhost/hasura-auth/blob/c328aa71ef2ce3e6e8fc1fbd8252975a25605dea/docker/dev/Dockerfile#L19

What is the intended way to run `nhost-auth` for development?

**Comment by elitan** [comment]
I kept the `.env` file now in the repo for dev purposes.

Developing should be as easy as:

```
yarn
yarn dev
```
