### ISSUE TITLE
hasura v3

### ISSUE THREAD

**Issue by andrewklau** [nhost/hasura-auth#566]
Is it in the pipeline for hasura-auth to support the new hasura v3?

**Comment by dbarrosop** [comment]
No, we don't currently have plans to support hasura v3.

**Comment by andrewklau** [comment]
Is the Go version of hasura-auth the work to decouple it from hasura?  It's something very interesting for us given the issue with naming_convention. Do you have any rough timeline for that?

Secondly, curious what is nhost plan for the graphql integration. Is the plan to continue with integration of hasura v2 for the graphql engine? v3 looks like a huge directional shift, and it seems uncertain how long hasura v2 would be maintained for.

Love what nhost does, so very curious to see where the direction will go since v3 is such a pivotal change
