### ISSUE TITLE
Expose Hasura-auth over GraphQL rather than "REST"

### ISSUE THREAD

**Issue by beepsoft** [nhost/hasura-auth#57]
I always wondered why the auth API-s are in REST and not in graphql, but I guess it is for compatibility, broader access and that you didn't want to manage two API-s.

Now as Hasura 2.1 is out and REST Connectors are public it should be fairly easy to provide builtin transformers for the auth API which would also expose it via Hasura:

https://hasura.io/blog/bring-rest-apis-as-a-data-source-to-hasura-announcing-rest-connectors-data-hub/

What do you think?

**Comment by elitan** [comment]
Looks interesting, but what's the benefit other than "exposing it via Hasura"?

Generally I like the separation of:

- Data: `/v1/graphql`
- Auth: `/v1/auth`
- Storage: `/v1/storage`
- Functions `/v1/functions`

**Comment by beepsoft** [comment]
I think it would make a nice unified API where all nhost related functionality (Hasura CRUD, auth, storage) is available via Graphql and so the clients don't need to use another kind of API (REST). It would make the overall nhost API much simpler:

- Data, auth, storage: `/v1/graphql`
- Functions: `/v1/functions`

In case of Javascript we have the nhost-js, but for mobile apps, we need to implement the auth/storage REST API.

I would find it more convenient to deal with a single paradigm - graphql - when using nhost. All graphql based tooling could be used eg. to generate a typed client and would not need to depend on nhost-js or a port of it to other platforms (although that would be really useful).

**Comment by nunopato** [comment]
> I agree, that there is a bit of a performance penalty, but even without this Hasura is a single point of failure as auth/storage already depends on Hasura.

That is correct, they depend on Hasura - my point is that the bigger the surface area, the more likely it is for it to become a point of failure.

We will try to come back to this soon, thanks for bringing this up.

**Comment by plmercereau** [comment]
We could weight the pros and cons between access through REST or GraphQL.

I guess it is also important to have a similar way to access the different Nhost services. As it is [not possible until now to upload files through Hasura](https://github.com/hasura/graphql-engine/issues/2419), storage will remain a REST service. It would be somehow inconsistent to handle one Nhost brick from REST while the others are 'proxied' by Hasura.

In my opinion the two main assets to expose auth and others as Hasura actions/remote schema would be:
- ability to define relations between auth schema/actions and the rest of the data
- to benefit from the Hasura permissions system
