### ISSUE TITLE
Allow users to use their own email provider and email templates

### ISSUE THREAD

**Issue by alveshelio** [nhost/hasura-auth#74]
Right now Nhost custom email templates isn't ready to go into production, as such and in order to not delay customers who are ready to go into production it would be nice if `nhost-auth` could provide some mechanism to allow us to handle email ourselves or let Nhost handle it.

Let's take an example here:
If we take a look at the sign up through email/password: https://github.com/nhost/hasura-auth/blob/main/src/routes/signup/email-password.ts
It checks the following
```ts
if (
    !ENV.AUTH_DISABLE_NEW_USERS &&
    ENV.AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED
  )
```
If it passes, it then sends an email to the user.

It would be nice if we could send an option to these endpoint that would give us a bit more control over email notifications, 
For example in this endpoint we could have in an option `manageEmail: boolean` and if `manageEmail` is `true` then it would skip sending the email and instead in
```ts
if (!ENV.AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED) {
    const signInResponse = await getSignInResponse({
      userId: user.id,
      checkMFA: false,
      emailURL: manageEmail ? `${ENV._SITE_URL}/ticket` : null
    });

    // return logged in session because user does not have to verify their email
    // to sign in
    return res.send(signInResponse);
  }

  return res.send({ session: null, mfa: null, emailURL: manageEmail ? `${ENV._SITE_URL}/ticket` : null });
};

```
With this, we could then retrieve the url with the ticket to embed in our email and we could use our own email templates.

**Comment by sangdth** [comment]
I would say a quick improvement could be to allow users to provide a template (hbs style or HTML for example) on nhost dashboard.

**Comment by plmercereau** [comment]
Salut @alveshelio,

If I understood well, you want the client to be able to get the email verification ticket without sending the email. In this case, it defeats the purpose of email verification, and I would rather allow users to authenticate without verification in setting `AUTH_EMAIL_SIGNIN_EMAIL_VERIFIED_REQUIRED` to `false`.
Unless I misunderstood, we won't implement this approach and I'm therefore closing this issue.

That being said, it is rather a missing feature in the Nhost console or CLI than in Hasura-auth. Although it is not a top priority yet, I opened [an issue](https://github.com/nhost/nhost/issues/120) to follow this up.

**Comment by plmercereau** [comment]
just bumped into the POST `/email-templates` endpoint:
For instance:
- add a `x-hasura-admin-secret` header
- post this:
```json
{
    "locale": "en",
    "subject": "un test",
    "id": "email-confirm-change"
}
```

IMO it is not ideal as the running `hasura-auth` container is supposed to be stateless, meaning the changes would be lost if it is replaced by another container. Still, could it temporary meet your need?
