### ISSUE TITLE
The `/email-templates` endpoint is not reliable with on a stateless container

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-auth#75]
This endpoint allows admin users to modify email templates files in the backend. However, these changes will be only stored in a container, which should be stateless.
As a result, it will create inconsistencies when scaling up horizontally. Also, changes would be lost when restarting/replacing the container.
We should come up with a better alternative, maybe in implementing the logic of the [`AUTH_EMAIL_TEMPLATE_FETCH_URL` ghost environment variable](https://github.com/nhost/hasura-auth/blob/main/src/utils/env.ts)

**Comment by elitan** [comment]
Yes, the idea was that the `AUTH_EMAIL_TEMPLATE_FETCH_URL` could be used to fetch an email template.

The parameters could be something like:

- type (e.g. Password reset)
- locale (e.g. en)

And the URL returns the subject and body for the email template.
