### ISSUE TITLE
Handle locale, allowedRoles and defaultRole too. It currently handle only redirectTo

### ISSUE THREAD

**Issue by regalstreak** [nhost/hasura-auth#80]
Currently we're supporting only `redirectTo`, add support for `locale`, `allowedRoles` and `defaultRole`

https://github.com/nhost/hasura-auth/blob/main/src/routes/signin/providers/utils.ts#L255-L258

Related: nhost/nhost#188

**Comment by elitan** [comment]
Fixes: https://github.com/nhost/nhost/issues/188
