### ISSUE TITLE
Request: Support other popular social logins

### ISSUE THREAD

**Issue by fungilation** [nhost/hasura-auth#92]
What's missing on popular ones:
- Discord
- Twitter
- Apple

In addition to these currently supported on nhost.io:

<img width="786" alt="Screen Shot 2022-02-03 at 7 11 15 PM" src="https://user-images.githubusercontent.com/3803466/152465947-3156b7c2-a199-4116-af97-7914b29916c9.png">

**Comment by sangdth** [comment]
I mentioned this one in [Discussion](https://github.com/nhost/nhost/discussions/118), as well as in recent community call.

**Comment by fungilation** [comment]
I see in `nhost/config.yaml` and README on this repo, that Twitter and Apple providers are included in hasura-auth now. What's missing for me is still
- Discord

and 1 more:
- Twitch

Since passport strategies are leveraged (https://github.com/nhost/hasura-auth/tree/main/src/routes/signin/providers), can these 2 be added with strategies I've integrated and tested elsewhere?
- https://github.com/oauth-everything/passport-discord
- https://github.com/d-relay/passport-twitch-strategy
