### ISSUE TITLE
Missing `v` at start of docker image tag

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-auth#93]
As an example: Hasura Auth v0.2.0 has the [tag `0.2.0`](https://hub.docker.com/layers/nhost/hasura-auth/0.2.0/images/sha256-28b924ba7fffc60d8e0f925c185c8b39d6abfd9da2fee649d87a4703efa41925?context=explore) instead of the expected `v0.2.0`.

**Comment by plmercereau** [comment]
What would be the rationale of not following semver?
https://semver.org/#is-v123-a-semantic-version

**Comment by elitan** [comment]
Hmm, maybe it's just Hasura who append their tags with `v`.

Seems like all other major images don't append `v` such as Ubuntu, Postgres, Node, Redis, etc.

Closing :)
