### ISSUE TITLE
Error reporting in case of wrong AUTH_JWT_CUSTOM_CLAIMS definitions

### ISSUE THREAD

**Issue by beepsoft** [nhost/hasura-auth#94]
Now when something is wrong with AUTH_JWT_CUSTOM_CLAIMS definition, eg. when it results in an erroneous Hasura graphql query, `/signin/email-password` doesn't report an error and simply doesn't generate the claims in the access token.

The only way to figure out what went wrong is to check the logs of the `nhost-auth` and `nhost-hasura` containers started by the `nhost cli`.

Either the authentication methods should return an error in this case or maybe generate an error message into the JWT token itself, since developers would probably check that while developing the custom claim definitions.

**Comment by beepsoft** [comment]
Somewhat related possible enhancement in the UI of Permission Variables, which generates the AUTH_JWT_CUSTOM_CLAIMS in the nhost console: it would be great if the UI provided autocomplete so that it would be practically impossible to enter wrong paths.

**Comment by plmercereau** [comment]
Hello,
Better late than never.
Yes, if the custom claim is errored, then it probably means its configuration needs to be adjusted. I don't think we should add error codes inside the JWT, it's better to go have a look at the logs while developing.
The logs for such an error has been improved - and they are now available in the Nhost Cloud.
Moreover the overall logs will be more readable when [this PR](https://github.com/nhost/hasura-auth/pull/256) will be released.
Closing for now
