### ISSUE TITLE
"null" value in custom claims when AUTH_JWT_CUSTOM_CLAIMS cannot generate a value

### ISSUE THREAD

**Issue by beepsoft** [nhost/hasura-auth#95]
When for a given user some claim cannot be calculated for the AUTH_JWT_CUSTOM_CLAIMS hasura-auth generates `"null"` string value for that claim, for example:

```json
{
  "https://hasura.io/jwt/claims": {
    "x-hasura-service-account-id": "1",
    "x-hasura-organization-id": "null",
    "x-hasura-allowed-roles": [
      "user",
      "me",
      "accountadmin"
    ],
    "x-hasura-default-role": "accountadmin",
    "x-hasura-user-id": "9b0ac75f-8d35-4a81-a3c2-1fc70a030dcc",
    "x-hasura-user-isAnonymous": "false"
  },
  "sub": "9b0ac75f-8d35-4a81-a3c2-1fc70a030dcc",
  "iss": "hasura-auth",
  "iat": 1645271890,
  "exp": 1645272790
}
```

In this case we have `"x-hasura-organization-id": "null"`, because the user trying to log in is not associated with an organization.

It may be better to leave out custom claim fields from the JWT, which result in `"null"` value, otherwise a Hasura permission rule may use this "null" value and accidently it may have a match, when it actually should not. Not in case of a numeric ID, but let say for a `username` field, which could have the valid value `"null"`.

**Comment by rikardkling** [comment]
Agree! Having null values for claims makes it unusable together with permissions. Would be great if we could just leave those values out instead.
